### ISSUE TITLE
Bad JSON keys

### ISSUE THREAD

**Issue by Eruyome** [trackpete/exiletools-indexer#111]
I think you should change these keys to camelCase without spaces
```
"properties": {
	"Map": {
		"Item Quantity": 29,
		"Item Rarity": 15,
		"Map Tier": 1
	}
}
```
itemQuantity
itemRarity
mapTier

**Comment by trackpete** [comment]
Those are derived straight from the original json automatically without
input, I'd change it but it would break any current tool. :(

**Comment by Eruyome** [comment]
It's bad and inconsistent, I'd rather break all current tools now but that's egoistical and not my call :p

**Comment by trackpete** [comment]
Let me clarify this a bit from a real computer instead of my phone:

In general, anything in Properties and Mods sections are extracted dynamically to provide forwards and backwards compatibility with the original item JSON and any other system. These are pulled directly from the data with minimal processing. These sections are typically designed for display in the original JSON data and are text elements in an array, and thus do not have camelCase names.

The other sections tend to have camelCase formatting because they are designed as actual keys. Anything I derive for use as an identifier key, I tend to name in camelCase as well.

Thus:

1. Any JSON with camelCase is typically expected to be processed in some way during search and display
2. Any JSON without camelCase that is directly extracted is typically expected to also be displayed as-is

Take the Map Properties in your example. If I reformat these keys:

1. Code must be added for each individual key to detected and reformat them, code which will break and need to be updated on any changes to the GGG JSON (i.e. "Item Quantity Bonus")
2. Code must be added to any client application or program to *reverse this action* and detect that the individual key is modified and add a display name to it

Moving all of these to individual camelCase would make a sexier JSON document, but "un-parsing" that would end up driving up the complexity even more.

`mods.explicit.socketedGemsHave8%ReducedManaCost : true` etc. is not a place we want to end up IMO. ;)

Finally, there is no official requirements/standards for JSON key naming that I'm aware of (just style guides), thus there's no such thing as "bad keys." 

So it makes sense to me to stick with basically making minimal changes to the origina JSON wherever possible.  Hope that explains better!

**Comment by Eruyome** [comment]
Yeah it does and I think I over reacted a bit because it gave me some troubles at the time. It's ok as it is right now.
