### ISSUE TITLE
Problem when using info.tokenized fullname

### ISSUE THREAD

**Issue by petterannerwall** [trackpete/exiletools-indexer#113]
Hello!

Im trying some queries with postman against the index and the example says to try searching for 'shavs' against the info,tokenized.fullName field but i cant seem to get it working, any suggestions on what im doing wrong here?

`{
	"query": {
		"bool": {
			"filter": [{
				"term": {
					"info.tokenized.fullName": "Shavs"
				}
			}, {
				"term": {
					"attributes.identified": true
				}
			}, {
				"term": {
					"attributes.corrupted": false
				}
			}]
		}
	},
	"sort": [{
		"shop.modified": {
			"order": "desc"
		}
	}],
	"size": 50
}`

**Comment by trackpete** [comment]
A couple of things:

1. The edge ngrams in that field are all lowercase, so you have to force your input to lower case

2. There is no "shavs" :) It's "shavronne's" so you will get matches for "shav" "shavr" "shavro" etc.

I'll update the documentation to indicate the ngrams are lowercase.

**Comment by petterannerwall** [comment]
Thanks for a fast reply!!, that solves the problem. Maybe you also know how should i treat the apostrophe as in "rat's nest"?

**Comment by trackpete** [comment]
I'm not sure about rat's nest, I might have to experiment a bit to see.

If you're just wondering about uniques, the best way to handle them IMO is
to pull a list of them and populate an optional search box.

You can run an aggregation query to get these names yourself and store them
in a user's browser cache for some period of time, or you can use this
undocumented API endpoint to do so:

http://api.exiletools.com/endpoints/list-field-values?field=info.fullName&filters=attributes.rarity:Unique

(that's not 100% working yet it might not have cross site requests enabled,
I'm only using it internally, will check on that today)

Letting players try to type in unique names is a recipe for disaster. They
never get it right.

**Comment by Eruyome** [comment]
If you want to let players type unique names you have to use a live input validation using regex and showing all valid results in a filtered list (or dropdown to select filtered items). Allowing users to ignore apostrophes in names is quite nice, too. Otherwise it is a disaster.

**Comment by trackpete** [comment]
The way I do this for the http://exiletools.com/uniques page is the best way IMO:

1. Get a list of unique items in the league and store it in local browser cache
2. Use a javascript system that allows searching and filtering directly on that array in memory

I'd rather people not implement typehead/etc. against the index when the cost of a once-every-ten-minutes population of an object with all of the unique item names that can be easily searched against using Select2/any other such thing is the big win.

The tokenization for full name searching is more intended for people to search for random stuff, not for unique item name searches. The way poe.trade does this is kinda annoying because as shown by this issue, people often forget the exact name - being able to type "shav" and have a select box show up is way better. 

![image](https://cloud.githubusercontent.com/assets/8779751/13532891/e3d87ea0-e1fb-11e5-9945-2d030f4d1b8e.png)

![image](https://cloud.githubusercontent.com/assets/8779751/13532895/e9fa4d90-e1fb-11e5-97c2-4919efcd5dbe.png)

**Comment by Eruyome** [comment]
I so hate what poe.trade does, I'm often in the situation where I want to search for an item and don't know the correct name or don't want to write apostrophes, that's so user unfriendly. You're doing what i basically meant, it is the best solution.
