### ISSUE TITLE
Temporary solution to approximately determine player online status

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#123]
Can we have a cached html page where the list of all players whom was seen in the river for the past _n_ hour(s)?

Tried this and it seems to be fast (500ms):
```
{
              "aggs": {
                "filtered": {
                  "filter" : { 
                                "bool" : {
                                    "should" : [
                                        {
                                            "range" : {
                                                "shop.updated" : {
                                                    "gte" : 'now-3h'
                                                }
                                            }
                                        },
                                        {
                                            "range" : {
                                                "shop.modified" : {
                                                    "gte" : 'now-3h'
                                                }
                                            }
                                        },
                                        {
                                            "range" : {
                                                "shop.added" : {
                                                    "gte" : 'now-3h'
                                                }
                                            }
                                        }
                                    ]
                                }
                             },
                  "aggs": {
                    "sellers": {
                          "terms": {
                            "field": "shop.sellerAccount",
                            size:100000
                          }
                        }
                  }
                }
              },
              "size": 0
            }
```

Would be great if we can have a cron job (or jenkins) that will run this query every _n_ minutes (5 mins?) then update the static page like http://exiletools.com/playeronline.html

Also, if it's not too much trouble, can we also merge-in the list of online players shown in the Ladder API:
http://api.exiletools.com/ladder?showAllOnline=1

curious side-question: is [this page](http://api.exiletools.com/ladder?showAllOnline=1) cached?

**Comment by thirdy** [comment]
Given the list of _approximately_ online players, adding them to your query to elastic is still fast (< 1sec). Tested with this request which took 998ms:

[exiletools-test-with-playerlist.txt](https://github.com/trackpete/exiletools-indexer/files/171465/exiletools-test-with-playerlist.txt)

**Comment by trackpete** [comment]
Finally got a chance to look at this in more detail. This is definitely something that should be performed by any client - the searches aren't massive heavy searches, so there's no need to try to set something up to do this on my end. It fits perfectly within the parameters of the API's to use them like this, and I'd like to see people doing things like this instead of me trying to set up and maintain regular queries. 

Until GGG releases a proper API, this solution makes sense and it probably fits within the scope of how the proper on-line API will work. Basically each client can generate this list internally every few minutes to filter the displayed results.

I would stick with filtering the results client side (not adjusting queries to the index) because that's how the official API will most likely work. You will request say 200 items then hit the official API to see which of those sellers are on-line and then filter the results to only display the 50 items from on-line sellers (and can perform a scroll or similar query to get more results, then filter those).

(the ladder all online does get cached on the front end for I believe 2min, but the backend data is only updated every 10min so..)
