### ISSUE TITLE
Enable scroll API?

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#125]
Trying out the scroll API described here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

I'm getting this error:

XMLHttpRequest cannot load http://api.exiletools.com/_search/scroll?scroll=30s. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

Maybe the scroll api is disabled?

**Comment by trackpete** [comment]
It doesn't look like I can configure this without re-thinking a lot of the way the API front end works. The problem is here:

```The URL should not include the index or type name — these are specified in the original search request instead.```

The reverse proxy for the API gateway specifies both the type and index to limit access, so people can't run external queries against some of the internal indexes I use. 

That said, in general it shouldn't be necessary to scroll much - I allow up to 20MB responses, which is generally enough to return 5-10k+ items. If you just want basic pagination and smaller response sizes, you can use the [from / size](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) parameters - scroll is more for parsing huge chunks of data =while ensuring the result set doesn't change, I think.

Anyway, let me know if that works, the from style for paging or just requesting a bigger up front chunk.

**Comment by thirdy** [comment]
Seems to work well:

http://exiletrade.github.io/?q=pureev+chest+80res+70life

I'd greatly appreciate if you can make a parameter to the ladder API to compress/minify the output on this request:

http://api.exiletools.com/ladder?league=perandus&short=1&accountName=Frajhamster:Croccodrilo:HolahHolahGetADollah:Wicked718:Mundl151:mglass93:DiabloHeat:AndySkandalo:Ellerean:Epictrash:zlobnik59:teemu92:maliciel:NoHomoSapien:euantrandom:Thor_of_Asgard:ididntmeantoks:Snorchi:Upsidwn:johny2030:Cryogenic_Sleep:wylickkus:TheBigDirty:MIKOLORT:kenshibqt:Player365

So I guess the scrolling API is not needed so far.

**Comment by trackpete** [comment]
Done: Add `onlineStats=1` to the query to get minified data back with only on-line related stats:

http://api.exiletools.com/ladder?league=perandus&short=1&accountName=Frajhamster:Croccodrilo:HolahHolahGetADollah:Wicked718:Mundl151:mglass93:DiabloHeat:AndySkandalo:Ellerean:Epictrash:zlobnik59:teemu92:maliciel:NoHomoSapien:euantrandom:Thor_of_Asgard:ididntmeantoks:Snorchi:Upsidwn:johny2030:Cryogenic_Sleep:wylickkus:TheBigDirty:MIKOLORT:kenshibqt:Player365&onlineStats=1

**Comment by thirdy** [comment]
Thanks!
