### ISSUE TITLE
Estimated Quality calculations for weapons are done incorrectly

### ISSUE THREAD

**Issue by kyri0** [trackpete/exiletools-indexer#146]
Heyo,

an ExileTrade user noticed (and I confirmed) that the "propertiesPseudo.Weapon.estimatedQ20.Physical DPS" calculation is being done incorrectly.

You can see the issue here: 
https://github.com/exiletrade/exiletrade/issues/94 #

**Comment by trackpete** [comment]
Oh no! Thank you for the report. I will try to look at this tomorrow!

**Comment by trackpete** [comment]
I'm a little confused about this. I've double checked all of my calculations and they are still accurate within rounding:

Here is a relevant code snippet:

```
$item{modsTotal}{"#% increased Physical Damage"} = 223;
$item{properties}{Quality} = 0;
$item{properties}{Weapon}{"Physical DPS"} = 362;

$item{propertiesPseudo}{Weapon}{estimatedQ20}{"Physical DPS"} += int($item{properties}{Weapon}{"Physical DPS"} / (1 + ($item{modsTotal}{"#% increased Physical Damage"} + $item{properties}{Quality}) / 100) * (1 + (($item{modsTotal}{"#% increased Physical Da
mage"} + 20) / 100)));

print $item{propertiesPseudo}{Weapon}{estimatedQ20}{"Physical DPS"}."\n";
```

```
perl x.pl
384
```

However, I tracked down that item in the index with 362PDPS and can confirm it came out at 434 Q20 PDPS. And a bunch of the other Q20 item calculations are wrong. What's happening here?

...

oh, shit. If I comment out the increased Physical mods line, I get 434. The mod must not be set or something.

**Comment by trackpete** [comment]
I'm an idiot. When I refactored the item processing code, I moved the Q20 pseudo code to BEFORE the mods are processed. Wow. None of the Q20 pseudo code is right as a result.

I moved the block of code back down to after the mods and the Q20 calculations are coming out properly now. I will be doing a full re-index shortly because of the stash uuid issues anyway, so this will be fixed in production shortly.
