### ISSUE TITLE
SSL Cert Expired

### ISSUE THREAD

**Issue by flyweight** [trackpete/exiletools-indexer#150]
The certificate for https://api.exiletools.com/ expired on June 30th.  Looks like it was issued by Let's Encrypt.  They have a lot of tools that help you automate cert renewal without human interaction that would help keep it up-to-date.

**Comment by trackpete** [comment]
This is fixed now. I use automated tools to update it but they keep breaking them. :p I've switched over to the new cerbot tool and it looks more reliable.

Note that https isn't officially "supported" at exiletools since there isn't a lot of reason to use it, I just set that up because some tools default to it.
