### ISSUE TITLE
Can I add Quality Calculations for Armour, PDPS, and Min/Max Physical Damage?

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#25]
I don't even know if this is possible without having a base item lookup table, so it's a possible enhancement.  I'm pretty sure the calculations make this impossible without base item information and I'd rather not deal with that.

**Comment by eps1lon** [comment]
rating_after = ceil(rating_before / (increases + q_before)) * (increases + quality_after)

Not 100% accurate because floating point operations but should be correct otherwise.

**Comment by trackpete** [comment]
Oh, that's an interesting approach - using the totalMods line for an increase to get at the base item instead of using a lookup table. That should be a lot easier to implement. I'll keep this on my to-do list then. ;) Cheers!

**Comment by trackpete** [comment]
Okay, let's game this out (finally):

Energy Shield: 
* #% increased Energy Shield
* #% increased Armour and Energy Shield
* #% increased Evasion and Energy Shield
* #% increased Armour, Evasion and Energy Shield

Armour:
* #% increased Armour
* #% increased Armour and Energy Shield
* #% increased Armour and Evasion
* #% increased Armour, Evasion and Energy Shield

Evasion:
* #% increased Evasion Rating
* #% increased Armour and Evasion
* #% increased Armour, Evasion and Energy Shield
* #% increased Evasion and Energy Shield

Use this to create new Pseudo Mods for:

* #% Total increased Armour
* #% Total increased Evasion
* #% Total increased Energy Shield

Then we can use that Pseudo value in the quality calculation.  DONE.

For weapons we don't have to do anything, we already have #% increased Physical Damage.

For armour stuff:

```
        if ($item{modsPseudo}{"#% Total increased $prop"} > 0) {
          $item{propertiesPseudo}{estimatedQ20}{"$prop"} += int($item{properties}{Armour}{"$prop"} / (1 + ($item{modsPseudo}{"#% Total increased $prop"} + $item{properties}{Quality}) / 100) * (1 + (($item{modsPseudo}{"#% Total increased $prop"} + 20) / 100
)));
        } else {
          $item{propertiesPseudo}{estimatedQ20}{"$prop"} = int(($item{properties}{Armour}{"$prop"} / (1 + $item{properties}{Quality} / 100)) * 1.20);
        }
```

Got 'er done.

**Comment by trackpete** [comment]
Weapons done now too! Woo. Thanks so much eps1lon, that made it so much easier, don't know why I waited so long to do this.

New properties in v3:

`pseudoProperties`
`pseudoProperties.Armour`
`pseudoProperties.Armour.estimatedQ20`
`pseudoProperties.Armour.estimatedQ20.Evasion Rating`
`pseudoProperties.Armour.estimatedQ20.Armour`
`pseudoProperties.Armour.estimatedQ20.Energy Shield`
`pseudoProperties.Weapon`
`pseudoProperties.Weapon.estimatedQ20`
`pseudoProperties.Weapon.estimatedQ20.Physical DPS`

**Comment by eps1lon** [comment]
So first of i dont really understand why you didnt just copy my formular. The if-else is unnecessary unless you didnt initalize `Total increased $prop` with 0 which you should to keep the code clean. Repeating formulars with that many parenthesis is quite dangerous.

I dont know your code but i dont understand why you dont need extra work for weapons. Quality should work the same with increases for Weapons and Armours.

And you altered my formular prob because i left out the last rounding part.

`RatingBeforeIncreases = ceil(rating / (1 + (increases + quality) / 100))`
`RatingWithQuality(quality) = floor(RatingBeforeIncreases * (1 + (increases + quality) / 100))`

The `ceil` is very important because it acts as a inverse to `floor`.

Example: 
Armour with base rating 587, +40% increased and 7quality will result in `587 * (1 + .4 + .7) = 862.89 = 862`.

With your formular estimated 20q would be (862 / 1.47) * 1.6 = 938.23 = 938.

But correct is ceil(862 / 1.47) * 1.6 = 587 * 1.6 = 939.2 = 939.

The difference is only 1 (which i think can still happen but i need to do some testing) but its still a difference that will occur most of the time.

On another matter it would be really nice if you would reference the issues in your code. You could create another bare branch for v3. Right now it feels really weird to talk about issues that are not that relevant to the actual code in the repository. That way i would've been able to just create a pull request.

**Comment by trackpete** [comment]
The reason there are separate chunks of code is because they're acting on calculations made at different parts in the parsing routine - "Physical DPS" doesn't actually exist in the item JSON, so we generate that in a different area and thus calculate the Q20 PDPS in a different stage. This does make me realize I don't calculate Q20 min/max damage values, which I probably should. 

Regardless the way properties are iterated in my code breaks out various sections, for example properties with min/max values are processed completely separately from properties with fixed values which are processed separate from properties with apparent boolean values/etc. I also needed to avoid calculating quality against every property (i.e. chance to block) so I specifically called out certain areas.

I did do a bunch of testing and verification with items (wasting a ton of whets and scraps hehe) and everything always came out within 1 point, so I expect the ceil bit is the reason - I honestly didn't understand that part. I'll do some more work to clean this up. 

Needless to say, I struggle a bit with coding math. ;)

The v3 branch stuff, the problem is that the entire chunk of code that handles rebuilding the JSON data includes a bunch of new attributes being analyzed that would violate the NDA if people saw it, but I really didn't expect it to be this long until it was announced so I didn't make any provisions for keeping those fields out. I thought about doing so, but then I'm like, oh they're supposed to announce it super soon, why waste the time? Six months later...  ;) haha. Let's hope it doesn't take that long, though they already missed the Friday release (which is a real bummer on their part).
